// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"bytes"
	"fmt"
	"io"
	"net/url"
	"strconv"
	"time"

	"github.com/oklog/ulid"
)

type CancelRequestResult struct {
	Success bool `json:"success"`
}

type CancelResponseResult struct {
	Success bool `json:"success"`
}

type ClearHTTPRequestLogResult struct {
	Success bool `json:"success"`
}

type CloseProjectResult struct {
	Success bool `json:"success"`
}

type DeleteProjectResult struct {
	Success bool `json:"success"`
}

type DeleteSenderRequestsResult struct {
	Success bool `json:"success"`
}

type HTTPHeader struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type HTTPHeaderInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type HTTPRequest struct {
	ID       ulid.ULID     `json:"id"`
	URL      *url.URL      `json:"url"`
	Method   HTTPMethod    `json:"method"`
	Proto    HTTPProtocol  `json:"proto"`
	Headers  []HTTPHeader  `json:"headers"`
	Body     *string       `json:"body,omitempty"`
	Response *HTTPResponse `json:"response,omitempty"`
}

type HTTPRequestLog struct {
	ID        ulid.ULID        `json:"id"`
	URL       string           `json:"url"`
	Method    HTTPMethod       `json:"method"`
	Proto     string           `json:"proto"`
	Headers   []HTTPHeader     `json:"headers"`
	Body      *string          `json:"body,omitempty"`
	Timestamp time.Time        `json:"timestamp"`
	Response  *HTTPResponseLog `json:"response,omitempty"`
}

type HTTPRequestLogFilter struct {
	OnlyInScope      bool    `json:"onlyInScope"`
	SearchExpression *string `json:"searchExpression,omitempty"`
}

type HTTPRequestLogFilterInput struct {
	OnlyInScope      *bool   `json:"onlyInScope,omitempty"`
	SearchExpression *string `json:"searchExpression,omitempty"`
}

type HTTPResponse struct {
	// Will be the same ID as its related request ID.
	ID           ulid.ULID    `json:"id"`
	Proto        HTTPProtocol `json:"proto"`
	StatusCode   int          `json:"statusCode"`
	StatusReason string       `json:"statusReason"`
	Body         *string      `json:"body,omitempty"`
	Headers      []HTTPHeader `json:"headers"`
}

type HTTPResponseLog struct {
	// Will be the same ID as its related request ID.
	ID           ulid.ULID    `json:"id"`
	Proto        HTTPProtocol `json:"proto"`
	StatusCode   int          `json:"statusCode"`
	StatusReason string       `json:"statusReason"`
	Body         *string      `json:"body,omitempty"`
	Headers      []HTTPHeader `json:"headers"`
}

type InterceptSettings struct {
	RequestsEnabled  bool    `json:"requestsEnabled"`
	ResponsesEnabled bool    `json:"responsesEnabled"`
	RequestFilter    *string `json:"requestFilter,omitempty"`
	ResponseFilter   *string `json:"responseFilter,omitempty"`
}

type ModifyRequestInput struct {
	ID             ulid.ULID         `json:"id"`
	URL            *url.URL          `json:"url"`
	Method         HTTPMethod        `json:"method"`
	Proto          HTTPProtocol      `json:"proto"`
	Headers        []HTTPHeaderInput `json:"headers,omitempty"`
	Body           *string           `json:"body,omitempty"`
	ModifyResponse *bool             `json:"modifyResponse,omitempty"`
}

type ModifyRequestResult struct {
	Success bool `json:"success"`
}

type ModifyResponseInput struct {
	RequestID    ulid.ULID         `json:"requestID"`
	Proto        HTTPProtocol      `json:"proto"`
	Headers      []HTTPHeaderInput `json:"headers,omitempty"`
	Body         *string           `json:"body,omitempty"`
	StatusCode   int               `json:"statusCode"`
	StatusReason string            `json:"statusReason"`
}

type ModifyResponseResult struct {
	Success bool `json:"success"`
}

type Mutation struct {
}

type Project struct {
	ID       ulid.ULID        `json:"id"`
	Name     string           `json:"name"`
	IsActive bool             `json:"isActive"`
	Settings *ProjectSettings `json:"settings"`
}

type ProjectSettings struct {
	Intercept *InterceptSettings `json:"intercept"`
}

type Query struct {
}

type ScopeHeader struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type ScopeHeaderInput struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type ScopeRule struct {
	URL    *string      `json:"url,omitempty"`
	Header *ScopeHeader `json:"header,omitempty"`
	Body   *string      `json:"body,omitempty"`
}

type ScopeRuleInput struct {
	URL    *string           `json:"url,omitempty"`
	Header *ScopeHeaderInput `json:"header,omitempty"`
	Body   *string           `json:"body,omitempty"`
}

type SenderRequest struct {
	ID                 ulid.ULID        `json:"id"`
	SourceRequestLogID *ulid.ULID       `json:"sourceRequestLogID,omitempty"`
	URL                *url.URL         `json:"url"`
	Method             HTTPMethod       `json:"method"`
	Proto              HTTPProtocol     `json:"proto"`
	Headers            []HTTPHeader     `json:"headers,omitempty"`
	Body               *string          `json:"body,omitempty"`
	Timestamp          time.Time        `json:"timestamp"`
	Response           *HTTPResponseLog `json:"response,omitempty"`
}

type SenderRequestFilter struct {
	OnlyInScope      bool    `json:"onlyInScope"`
	SearchExpression *string `json:"searchExpression,omitempty"`
}

type SenderRequestFilterInput struct {
	OnlyInScope      *bool   `json:"onlyInScope,omitempty"`
	SearchExpression *string `json:"searchExpression,omitempty"`
}

type SenderRequestInput struct {
	ID      *ulid.ULID        `json:"id,omitempty"`
	URL     *url.URL          `json:"url"`
	Method  *HTTPMethod       `json:"method,omitempty"`
	Proto   *HTTPProtocol     `json:"proto,omitempty"`
	Headers []HTTPHeaderInput `json:"headers,omitempty"`
	Body    *string           `json:"body,omitempty"`
}

type UpdateInterceptSettingsInput struct {
	RequestsEnabled  bool    `json:"requestsEnabled"`
	ResponsesEnabled bool    `json:"responsesEnabled"`
	RequestFilter    *string `json:"requestFilter,omitempty"`
	ResponseFilter   *string `json:"responseFilter,omitempty"`
}

type HTTPMethod string

const (
	HTTPMethodGet     HTTPMethod = "GET"
	HTTPMethodHead    HTTPMethod = "HEAD"
	HTTPMethodPost    HTTPMethod = "POST"
	HTTPMethodPut     HTTPMethod = "PUT"
	HTTPMethodDelete  HTTPMethod = "DELETE"
	HTTPMethodConnect HTTPMethod = "CONNECT"
	HTTPMethodOptions HTTPMethod = "OPTIONS"
	HTTPMethodTrace   HTTPMethod = "TRACE"
	HTTPMethodPatch   HTTPMethod = "PATCH"
)

var AllHTTPMethod = []HTTPMethod{
	HTTPMethodGet,
	HTTPMethodHead,
	HTTPMethodPost,
	HTTPMethodPut,
	HTTPMethodDelete,
	HTTPMethodConnect,
	HTTPMethodOptions,
	HTTPMethodTrace,
	HTTPMethodPatch,
}

func (e HTTPMethod) IsValid() bool {
	switch e {
	case HTTPMethodGet, HTTPMethodHead, HTTPMethodPost, HTTPMethodPut, HTTPMethodDelete, HTTPMethodConnect, HTTPMethodOptions, HTTPMethodTrace, HTTPMethodPatch:
		return true
	}
	return false
}

func (e HTTPMethod) String() string {
	return string(e)
}

func (e *HTTPMethod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HTTPMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HttpMethod", str)
	}
	return nil
}

func (e HTTPMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HTTPMethod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HTTPMethod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type HTTPProtocol string

const (
	HTTPProtocolHTTP10 HTTPProtocol = "HTTP10"
	HTTPProtocolHTTP11 HTTPProtocol = "HTTP11"
	HTTPProtocolHTTP20 HTTPProtocol = "HTTP20"
)

var AllHTTPProtocol = []HTTPProtocol{
	HTTPProtocolHTTP10,
	HTTPProtocolHTTP11,
	HTTPProtocolHTTP20,
}

func (e HTTPProtocol) IsValid() bool {
	switch e {
	case HTTPProtocolHTTP10, HTTPProtocolHTTP11, HTTPProtocolHTTP20:
		return true
	}
	return false
}

func (e HTTPProtocol) String() string {
	return string(e)
}

func (e *HTTPProtocol) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HTTPProtocol(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HttpProtocol", str)
	}
	return nil
}

func (e HTTPProtocol) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HTTPProtocol) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HTTPProtocol) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
