package exttool

// builtinTools is the Sn1per-style arsenal. Each runs only if its binary is
// found on PATH. {target} is substituted with the user-supplied target; extra
// args entered in the UI are appended. No shell is used.
var builtinTools = []Tool{
	// --- Port / network scanning ---
	{Name: "nmap", Binary: "nmap", Category: "portscan", NeedsTarget: true,
		Description: "Service/version + default-script scan (top 1000 ports).",
		Args:        []string{"-sV", "-sC", "-T4", "--top-ports", "1000", "{target}"}},
	{Name: "nmap-full", Binary: "nmap", Category: "portscan", NeedsTarget: true,
		Description: "Full TCP port scan with service detection.",
		Args:        []string{"-sV", "-p-", "-T4", "{target}"}},
	{Name: "masscan", Binary: "masscan", Category: "portscan", NeedsTarget: true,
		Description: "Fast Internet-scale port scanner.",
		Args:        []string{"-p1-65535", "--rate", "1000", "{target}"}},

	// --- Web scanning ---
	{Name: "nikto", Binary: "nikto", Category: "web", NeedsTarget: true,
		Description: "Web server misconfiguration / known-vuln scanner.",
		Args:        []string{"-host", "{target}"}},
	{Name: "whatweb", Binary: "whatweb", Category: "web", NeedsTarget: true,
		Description: "Web technology fingerprinter.",
		Args:        []string{"{target}"}},
	{Name: "wafw00f", Binary: "wafw00f", Category: "web", NeedsTarget: true,
		Description: "Web application firewall fingerprinter.",
		Args:        []string{"{target}"}},
	{Name: "wpscan", Binary: "wpscan", Category: "web", NeedsTarget: true,
		Description: "WordPress security scanner.",
		Args:        []string{"--url", "{target}", "--no-banner"}},
	{Name: "nuclei", Binary: "nuclei", Category: "vuln", NeedsTarget: true,
		Description: "Template-based vulnerability scanner.",
		Args:        []string{"-u", "{target}", "-silent"}},
	{Name: "gobuster", Binary: "gobuster", Category: "web", NeedsTarget: true,
		Description: "Directory/file brute-forcer (pass -w <wordlist> in extra args).",
		Args:        []string{"dir", "-u", "{target}"}},
	{Name: "feroxbuster", Binary: "feroxbuster", Category: "web", NeedsTarget: true,
		Description: "Fast recursive content discovery.",
		Args:        []string{"-u", "{target}"}},
	{Name: "ffuf", Binary: "ffuf", Category: "web", NeedsTarget: true,
		Description: "Web fuzzer (pass -w <wordlist> in extra args).",
		Args:        []string{"-u", "{target}"}},

	// --- Subdomain / OSINT ---
	{Name: "subfinder", Binary: "subfinder", Category: "subdomain", NeedsTarget: true,
		Description: "Passive subdomain enumeration.",
		Args:        []string{"-d", "{target}", "-silent"}},
	{Name: "amass", Binary: "amass", Category: "subdomain", NeedsTarget: true,
		Description: "In-depth attack-surface / subdomain mapping.",
		Args:        []string{"enum", "-passive", "-d", "{target}"}},
	{Name: "sublist3r", Binary: "sublist3r", Category: "subdomain", NeedsTarget: true,
		Description: "Subdomain enumeration via search engines.",
		Args:        []string{"-d", "{target}"}},
	{Name: "theharvester", Binary: "theHarvester", Category: "osint", NeedsTarget: true,
		Description: "Emails, subdomains, and hosts from public sources.",
		Args:        []string{"-d", "{target}", "-b", "all"}},
	{Name: "fierce", Binary: "fierce", Category: "dns", NeedsTarget: true,
		Description: "DNS reconnaissance / subdomain brute.",
		Args:        []string{"--domain", "{target}"}},

	// --- TLS ---
	{Name: "sslscan", Binary: "sslscan", Category: "tls", NeedsTarget: true,
		Description: "Enumerate SSL/TLS ciphers and protocols.",
		Args:        []string{"{target}"}},
	{Name: "testssl", Binary: "testssl.sh", Category: "tls", NeedsTarget: true,
		Description: "Thorough TLS configuration testing.",
		Args:        []string{"{target}"}},

	// --- DNS / info ---
	{Name: "dnsrecon", Binary: "dnsrecon", Category: "dns", NeedsTarget: true,
		Description: "DNS enumeration and zone analysis.",
		Args:        []string{"-d", "{target}"}},
	{Name: "dig", Binary: "dig", Category: "dns", NeedsTarget: true,
		Description: "DNS lookup (ANY by default).",
		Args:        []string{"{target}", "ANY"}},
	{Name: "whois", Binary: "whois", Category: "info", NeedsTarget: true,
		Description: "WHOIS registration lookup.",
		Args:        []string{"{target}"}},

	// --- SMB ---
	{Name: "enum4linux", Binary: "enum4linux", Category: "smb", NeedsTarget: true,
		Description: "SMB / Windows enumeration.",
		Args:        []string{"-a", "{target}"}},
	{Name: "smbmap", Binary: "smbmap", Category: "smb", NeedsTarget: true,
		Description: "SMB share enumeration.",
		Args:        []string{"-H", "{target}"}},

	// --- Brute force / injection / exploit ---
	{Name: "hydra", Binary: "hydra", Category: "brute", NeedsTarget: true,
		Description: "Credential brute-forcer (supply service + -L/-P in extra args).",
		Args:        []string{"{target}"}},
	{Name: "sqlmap", Binary: "sqlmap", Category: "vuln", NeedsTarget: true,
		Description: "Automatic SQL-injection detection/exploitation.",
		Args:        []string{"-u", "{target}", "--batch"}},
	{Name: "searchsploit", Binary: "searchsploit", Category: "exploit", NeedsTarget: true,
		Description: "Search Exploit-DB (target = search term).",
		Args:        []string{"{target}"}},
	{Name: "gowitness", Binary: "gowitness", Category: "screenshot", NeedsTarget: true,
		Description: "Screenshot a URL.",
		Args:        []string{"single", "{target}"}},

	// --- ProjectDiscovery / reNgine / Osmedeus / reconFTW arsenal ---
	{Name: "httpx", Binary: "httpx", Category: "web", NeedsTarget: true,
		Description: "Fast HTTP probe: status, title, tech, CDN (target = host or file).",
		Args:        []string{"-u", "{target}", "-title", "-tech-detect", "-status-code", "-silent"}},
	{Name: "naabu", Binary: "naabu", Category: "portscan", NeedsTarget: true,
		Description: "Fast SYN/CONNECT port scanner (ProjectDiscovery).",
		Args:        []string{"-host", "{target}", "-silent"}},
	{Name: "dnsx", Binary: "dnsx", Category: "dns", NeedsTarget: true,
		Description: "Fast DNS toolkit (resolve, brute, records).",
		Args:        []string{"-d", "{target}", "-silent"}},
	{Name: "katana", Binary: "katana", Category: "web", NeedsTarget: true,
		Description: "Next-gen crawler / endpoint discovery.",
		Args:        []string{"-u", "{target}", "-silent"}},
	{Name: "tlsx", Binary: "tlsx", Category: "tls", NeedsTarget: true,
		Description: "TLS data grabber (SANs, versions, ciphers).",
		Args:        []string{"-u", "{target}", "-silent"}},
	{Name: "notify", Binary: "notify", Category: "info", NeedsTarget: false,
		Description: "Send results to Slack/Discord/Telegram (configure ~/.config/notify).",
		Args:        []string{"-silent"}},
	{Name: "assetfinder", Binary: "assetfinder", Category: "subdomain", NeedsTarget: true,
		Description: "Find domains/subdomains related to a target.",
		Args:        []string{"{target}"}},
	{Name: "findomain", Binary: "findomain", Category: "subdomain", NeedsTarget: true,
		Description: "Fast subdomain enumerator.",
		Args:        []string{"-t", "{target}"}},
	{Name: "gau", Binary: "gau", Category: "web", NeedsTarget: true,
		Description: "Fetch known URLs from Wayback/OTX/CommonCrawl.",
		Args:        []string{"{target}"}},
	{Name: "waybackurls", Binary: "waybackurls", Category: "web", NeedsTarget: true,
		Description: "Fetch archived URLs for a domain.",
		Args:        []string{"{target}"}},
	{Name: "hakrawler", Binary: "hakrawler", Category: "web", NeedsTarget: true,
		Description: "Fast web crawler for endpoints/assets.",
		Args:        []string{"-url", "{target}"}},
	{Name: "gospider", Binary: "gospider", Category: "web", NeedsTarget: true,
		Description: "Fast web spider written in Go.",
		Args:        []string{"-s", "{target}"}},
	{Name: "dalfox", Binary: "dalfox", Category: "vuln", NeedsTarget: true,
		Description: "Powerful XSS scanner/parameter analyzer.",
		Args:        []string{"url", "{target}"}},
	{Name: "arjun", Binary: "arjun", Category: "web", NeedsTarget: true,
		Description: "HTTP parameter discovery.",
		Args:        []string{"-u", "{target}"}},
	{Name: "crlfuzz", Binary: "crlfuzz", Category: "vuln", NeedsTarget: true,
		Description: "CRLF injection scanner.",
		Args:        []string{"-u", "{target}"}},
	{Name: "subjack", Binary: "subjack", Category: "subdomain", NeedsTarget: true,
		Description: "Subdomain takeover checker (target = file of subdomains).",
		Args:        []string{"-w", "{target}", "-ssl"}},
	{Name: "subzy", Binary: "subzy", Category: "subdomain", NeedsTarget: true,
		Description: "Subdomain takeover checker.",
		Args:        []string{"run", "--target", "{target}"}},
	{Name: "rustscan", Binary: "rustscan", Category: "portscan", NeedsTarget: true,
		Description: "Ultra-fast port scanner (pipes into nmap).",
		Args:        []string{"-a", "{target}"}},
	{Name: "dirsearch", Binary: "dirsearch", Category: "web", NeedsTarget: true,
		Description: "Web path brute-forcer.",
		Args:        []string{"-u", "{target}"}},
	{Name: "gitleaks", Binary: "gitleaks", Category: "vuln", NeedsTarget: true,
		Description: "Detect secrets in a git repo (target = path).",
		Args:        []string{"detect", "--source", "{target}", "-v"}},
	{Name: "trufflehog", Binary: "trufflehog", Category: "vuln", NeedsTarget: true,
		Description: "Find leaked credentials (target = git URL or filesystem path).",
		Args:        []string{"filesystem", "{target}"}},
	{Name: "cero", Binary: "cero", Category: "tls", NeedsTarget: true,
		Description: "Scrape domain names from TLS certificates.",
		Args:        []string{"{target}"}},
	{Name: "cdncheck", Binary: "cdncheck", Category: "info", NeedsTarget: true,
		Description: "Identify whether a host is behind a CDN/WAF/cloud.",
		Args:        []string{"-i", "{target}"}},
	{Name: "puredns", Binary: "puredns", Category: "dns", NeedsTarget: true,
		Description: "Fast accurate DNS resolver/brute (needs -r resolvers in extra).",
		Args:        []string{"bruteforce", "{target}"}},
	{Name: "shuffledns", Binary: "shuffledns", Category: "dns", NeedsTarget: true,
		Description: "massdns wrapper for subdomain resolution.",
		Args:        []string{"-d", "{target}", "-silent"}},
	{Name: "s3scanner", Binary: "s3scanner", Category: "osint", NeedsTarget: true,
		Description: "Find open S3 buckets for a target.",
		Args:        []string{"scan", "--bucket", "{target}"}},
	{Name: "jaeles", Binary: "jaeles", Category: "vuln", NeedsTarget: true,
		Description: "Signature-based web vulnerability scanner.",
		Args:        []string{"scan", "-u", "{target}"}},
	{Name: "nuclei-templates-update", Binary: "nuclei", Category: "vuln", NeedsTarget: false,
		Description: "Update the nuclei community templates.",
		Args:        []string{"-update-templates"}},

	// --- Orchestrators + extra recon ---
	{Name: "osmedeus", Binary: "osmedeus", Category: "subdomain", NeedsTarget: true,
		Description: "Osmedeus all-in-one recon/scan workflow engine.",
		Args:        []string{"scan", "-t", "{target}"}},
	{Name: "ctfr", Binary: "ctfr", Category: "subdomain", NeedsTarget: true,
		Description: "Subdomains from Certificate Transparency logs.",
		Args:        []string{"-d", "{target}"}},
	{Name: "gotator", Binary: "gotator", Category: "dns", NeedsTarget: true,
		Description: "Generate DNS permutation wordlists (target = subdomains file).",
		Args:        []string{"-sub", "{target}"}},
	{Name: "dnsgen", Binary: "dnsgen", Category: "dns", NeedsTarget: true,
		Description: "Generate domain permutations (target = file of domains).",
		Args:        []string{"{target}"}},
	{Name: "mapcidr", Binary: "mapcidr", Category: "info", NeedsTarget: true,
		Description: "Expand/aggregate CIDR ranges.",
		Args:        []string{"-cidr", "{target}"}},
	{Name: "uncover", Binary: "uncover", Category: "osint", NeedsTarget: true,
		Description: "Discover hosts via Shodan/Censys/Fofa (target = query).",
		Args:        []string{"-q", "{target}"}},
	{Name: "interactsh-client", Binary: "interactsh-client", Category: "vuln", NeedsTarget: false,
		Description: "OOB interaction (OAST) client for blind vuln testing.",
		Args:        []string{}},
	{Name: "kiterunner", Binary: "kr", Category: "web", NeedsTarget: true,
		Description: "API endpoint/route discovery (kr scan).",
		Args:        []string{"scan", "{target}"}},
	{Name: "x8", Binary: "x8", Category: "web", NeedsTarget: true,
		Description: "Hidden HTTP parameter discovery.",
		Args:        []string{"-u", "{target}"}},
	{Name: "wafw00f-list", Binary: "wafw00f", Category: "web", NeedsTarget: false,
		Description: "List all WAFs wafw00f can detect.",
		Args:        []string{"-l"}},

	// --- Trivy (container/fs/repo/IaC vuln + misconfig scanner) ---
	{Name: "trivy-image", Binary: "trivy", Category: "vuln", NeedsTarget: true,
		Description: "Scan a container image for vulnerabilities (target = image ref).",
		Args:        []string{"image", "{target}"}},
	{Name: "trivy-fs", Binary: "trivy", Category: "vuln", NeedsTarget: true,
		Description: "Scan a filesystem path for vulns + misconfigs + secrets.",
		Args:        []string{"fs", "{target}"}},
	{Name: "trivy-repo", Binary: "trivy", Category: "vuln", NeedsTarget: true,
		Description: "Scan a git repository for vulns + secrets (target = repo URL).",
		Args:        []string{"repo", "{target}"}},
	{Name: "trivy-config", Binary: "trivy", Category: "vuln", NeedsTarget: true,
		Description: "Scan IaC/config (Terraform, k8s, Dockerfile) for misconfigs.",
		Args:        []string{"config", "{target}"}},
}
