package wafdetect

// signature is a WAF fingerprint. All string matches are lowercase-substring.
type signature struct {
	name    string
	server  string            // substring of the Server header
	headers map[string]string // header name -> required lowercase substring ("" = presence)
	cookies []string          // lowercase cookie-name substrings
	body    []string          // lowercase body substrings
}

var signatures = []signature{
	{
		name:    "Cloudflare",
		server:  "cloudflare",
		headers: map[string]string{"CF-RAY": "", "CF-Cache-Status": ""},
		cookies: []string{"__cfduid", "__cf_bm", "cf_clearance"},
		body:    []string{"attention required! | cloudflare", "cloudflare ray id"},
	},
	{
		name:    "Akamai",
		server:  "akamaighost",
		headers: map[string]string{"X-Akamai-Transformed": ""},
		body:    []string{"akamaighost", "reference #"},
	},
	{
		name:    "Imperva Incapsula",
		headers: map[string]string{"X-Iinfo": "", "X-CDN": "incapsula"},
		cookies: []string{"incap_ses", "visid_incap"},
		body:    []string{"incapsula", "_incapsula_resource"},
	},
	{
		name:    "Sucuri CloudProxy",
		server:  "sucuri",
		headers: map[string]string{"X-Sucuri-ID": "", "X-Sucuri-Cache": ""},
		body:    []string{"sucuri website firewall", "access denied - sucuri"},
	},
	{
		name:    "F5 BIG-IP ASM",
		server:  "big-ip",
		cookies: []string{"bigipserver", "ts0"},
		body:    []string{"the requested url was rejected"},
	},
	{
		name:    "ModSecurity",
		server:  "mod_security",
		body:    []string{"mod_security", "this error was generated by mod_security", "not acceptable!"},
	},
	{
		name:    "AWS WAF / ELB",
		server:  "awselb",
		cookies: []string{"awsalb", "aws-waf-token"},
		body:    []string{"request blocked", "aws waf"},
	},
	{
		name:    "Barracuda",
		cookies: []string{"barra_counter_session", "barracuda_"},
		body:    []string{"barracuda"},
	},
	{
		name:    "Citrix NetScaler",
		headers: map[string]string{"Via": "ns-cache"},
		cookies: []string{"citrix_ns_id", "ns_af"},
		body:    []string{"ns_af"},
	},
	{
		name:    "Fortinet FortiWeb",
		cookies: []string{"fortiwafsid"},
		body:    []string{"fortiweb", ".fgd_icon"},
	},
	{
		name:   "DDoS-Guard",
		server: "ddos-guard",
		body:   []string{"ddos-guard"},
	},
	{
		name: "Wordfence",
		body: []string{"generated by wordfence", "your access to this site has been limited"},
	},
}
